"""initial schema: system events + economic data tables

Revision ID: 02774e3e8b80
Revises: 
Create Date: 2026-09-11 08:31:38.593362

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '02774e3e8b80'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_created_at'), 'system_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_table('economic_series',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('units', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'code', name='uq_series_source_code')
    )
    op.create_index(op.f('ix_economic_series_code'), 'economic_series', ['code'], unique=False)
    op.create_table('economic_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('series_id', sa.String(length=36), nullable=False),
    sa.Column('observation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('realtime_start', sa.Date(), nullable=False),
    sa.Column('realtime_end', sa.Date(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['economic_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'observation_date', 'realtime_start', name='uq_observation_vintage')
    )
    op.create_index(op.f('ix_economic_observations_observation_date'), 'economic_observations', ['observation_date'], unique=False)
    op.create_index(op.f('ix_economic_observations_realtime_start'), 'economic_observations', ['realtime_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_economic_observations_realtime_start'), table_name='economic_observations')
    op.drop_index(op.f('ix_economic_observations_observation_date'), table_name='economic_observations')
    op.drop_table('economic_observations')
    op.drop_index(op.f('ix_economic_series_code'), table_name='economic_series')
    op.drop_table('economic_series')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_index(op.f('ix_system_events_created_at'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
