"""add risk governance tables

Revision ID: 256cfc7ed046
Revises: ce0a983b0277
Create Date: 2026-09-11 11:18:06.788709

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '256cfc7ed046'
down_revision: str | None = 'ce0a983b0277'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switch_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kill_switch_events_created_at'), 'kill_switch_events', ['created_at'], unique=False)
    op.create_table('risk_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_risk_per_trade_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('max_portfolio_heat_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('max_single_asset_exposure_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('min_quality_grade', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_configs')
    op.drop_index(op.f('ix_kill_switch_events_created_at'), table_name='kill_switch_events')
    op.drop_table('kill_switch_events')
    # ### end Alembic commands ###
