"""add position risk_pct and daily loss limit

Revision ID: 74f296a63a5d
Revises: a6f3ecfe85c6
Create Date: 2026-09-11 16:06:28.635924

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '74f296a63a5d'
down_revision: str | None = 'a6f3ecfe85c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # server_default backfills existing rows (positions/risk_configs that
    # already existed before these columns did) so this migration works on
    # a database with real data in it, not just an empty one. Discovered
    # the hard way: this originally had no server_default and crashed
    # Postgres with a NOT NULL violation on a real, populated database.
    op.add_column(
        'positions',
        sa.Column('risk_pct', sa.Numeric(precision=6, scale=3), nullable=False, server_default='0'),
    )
    op.add_column(
        'risk_configs',
        sa.Column(
            'max_daily_loss_pct', sa.Numeric(precision=6, scale=3), nullable=False, server_default='3.0'
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_configs', 'max_daily_loss_pct')
    op.drop_column('positions', 'risk_pct')
    # ### end Alembic commands ###
