"""add position risk_pct and daily loss limit

Revision ID: 74f296a63a5d
Revises: a6f3ecfe85c6
Create Date: 2026-09-11 16:06:28.635924

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '74f296a63a5d'
down_revision: str | None = 'a6f3ecfe85c6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('risk_pct', sa.Numeric(precision=6, scale=3), nullable=False))
    op.add_column('risk_configs', sa.Column('max_daily_loss_pct', sa.Numeric(precision=6, scale=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_configs', 'max_daily_loss_pct')
    op.drop_column('positions', 'risk_pct')
    # ### end Alembic commands ###
