"""add positions table and order macro score

Revision ID: a6f3ecfe85c6
Revises: aa066738001f
Create Date: 2026-09-11 15:14:10.095857

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a6f3ecfe85c6'
down_revision: str | None = 'aa066738001f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('initial_stop_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('entry_classification', sa.String(length=30), nullable=True),
    sa.Column('entry_quality_grade', sa.String(length=1), nullable=True),
    sa.Column('entry_gold_macro_score', sa.Integer(), nullable=True),
    sa.Column('entry_thesis', sa.Text(), nullable=False),
    sa.Column('current_stop_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close_reason', sa.String(length=30), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_positions_opened_at'), 'positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_positions_status'), 'positions', ['status'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.add_column('orders', sa.Column('entry_gold_macro_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'entry_gold_macro_score')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_status'), table_name='positions')
    op.drop_index(op.f('ix_positions_opened_at'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
