"""add orders table

Revision ID: aa066738001f
Revises: 256cfc7ed046
Create Date: 2026-09-11 11:32:05.690701

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'aa066738001f'
down_revision: str | None = '256cfc7ed046'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('filled_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('units', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('risk_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('risk_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('quality_grade', sa.String(length=1), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=True),
    sa.Column('rejection_reasons', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
