"""add market bars table

Revision ID: ce0a983b0277
Revises: 02774e3e8b80
Create Date: 2026-09-11 10:28:35.756998

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ce0a983b0277'
down_revision: str | None = '02774e3e8b80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_bars',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('bar_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'interval', 'bar_time', name='uq_market_bar')
    )
    op.create_index(op.f('ix_market_bars_bar_time'), 'market_bars', ['bar_time'], unique=False)
    op.create_index(op.f('ix_market_bars_interval'), 'market_bars', ['interval'], unique=False)
    op.create_index(op.f('ix_market_bars_symbol'), 'market_bars', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_bars_symbol'), table_name='market_bars')
    op.drop_index(op.f('ix_market_bars_interval'), table_name='market_bars')
    op.drop_index(op.f('ix_market_bars_bar_time'), table_name='market_bars')
    op.drop_table('market_bars')
    # ### end Alembic commands ###
